import { describe, expect, it } from "vitest";

import { planInitialTodos } from "@/server/meta-agent/todo-driven/planner";

function buildParallelPlanJson() {
  return JSON.stringify({
    todos: [
      {
        id: "todo_scope",
        title: "Define search scope and allocation",
        description: "Clarify the target topic, acceptance criteria, and how two parallel workers should split the task.",
        priority: "critical",
        capability_type: "planning",
        assignee: "single_executor",
        depends_on: [],
        acceptance_criteria: [
          "scope is explicit",
          "parallel ownership is defined",
        ],
        input_refs: [],
      },
      {
        id: "todo_collect_1",
        title: "Parallel collection batch 1",
        description: "Handle the first half of the requested materials and keep the batch independent.",
        priority: "high",
        capability_type: "collection",
        assignee: "single_executor",
        depends_on: ["todo_scope"],
        acceptance_criteria: [
          "batch 1 result is complete",
          "batch 1 output is structured for merge",
        ],
        input_refs: [],
      },
      {
        id: "todo_collect_2",
        title: "Parallel collection batch 2",
        description: "Handle the second half of the requested materials and keep the batch independent.",
        priority: "high",
        capability_type: "collection",
        assignee: "single_executor",
        depends_on: ["todo_scope"],
        acceptance_criteria: [
          "batch 2 result is complete",
          "batch 2 output is structured for merge",
        ],
        input_refs: [],
      },
      {
        id: "todo_merge_results",
        title: "Merge parallel results",
        description: "Combine the two batches and remove overlap.",
        priority: "high",
        capability_type: "merge",
        assignee: "single_executor",
        depends_on: ["todo_collect_1", "todo_collect_2"],
        acceptance_criteria: [
          "merged result is complete",
          "duplicates are removed",
        ],
        input_refs: [],
      },
      {
        id: "todo_deliver",
        title: "Deliver final result",
        description: "Deliver the final merged result in a readable format.",
        priority: "high",
        capability_type: "writing",
        assignee: "single_executor",
        depends_on: ["todo_merge_results"],
        acceptance_criteria: [
          "final result is readable",
          "final result uses the merged output",
        ],
        input_refs: [],
      },
    ],
  });
}

describe("todo planner parallel planning", () => {
  it("accepts explicit parallel plans generated by the LLM", async () => {
    const todos = await planInitialTodos(
      "Download 20 agent reinforcement learning papers with two parallel subagents.",
      undefined,
      {
        invokeLlm: async () => buildParallelPlanJson(),
      },
    );

    expect(todos).toHaveLength(5);
    expect(todos.filter((todo) => todo.capability_type === "collection")).toHaveLength(2);
    expect(todos.find((todo) => todo.id === "todo_merge_results")?.depends_on).toEqual([
      "todo_collect_1",
      "todo_collect_2",
    ]);
  });

  it("does not require main-chain Chinese heuristics when the LLM returns a valid Chinese plan", async () => {
    const todos = await planInitialTodos(
      "下载20篇agent rl的论文，要求两个子agent并行处理",
      undefined,
      {
        invokeLlm: async () => JSON.stringify({
          todos: [
            {
              id: "todo_scope",
              title: "明确范围",
              description: "明确主题、筛选标准、并行分工方式以及最终交付格式。",
              priority: "critical",
              capability_type: "planning",
              assignee: "single_executor",
              depends_on: [],
              acceptance_criteria: ["范围与筛选标准明确", "并行分工方案明确可执行"],
              input_refs: [],
            },
            {
              id: "todo_collect_1",
              title: "批次一收集",
              description: "负责第一批材料收集，并整理成后续可合并的结构化结果。",
              priority: "high",
              capability_type: "collection",
              assignee: "single_executor",
              depends_on: ["todo_scope"],
              acceptance_criteria: ["批次一收集结果完整", "批次一输出结构可合并"],
              input_refs: [],
            },
            {
              id: "todo_collect_2",
              title: "批次二收集",
              description: "负责第二批材料收集，并整理成后续可合并的结构化结果。",
              priority: "high",
              capability_type: "collection",
              assignee: "single_executor",
              depends_on: ["todo_scope"],
              acceptance_criteria: ["批次二收集结果完整", "批次二输出结构可合并"],
              input_refs: [],
            },
            {
              id: "todo_merge_results",
              title: "合并结果",
              description: "合并两个批次结果并去重，形成一个统一的中间结果。",
              priority: "high",
              capability_type: "merge",
              assignee: "single_executor",
              depends_on: ["todo_collect_1", "todo_collect_2"],
              acceptance_criteria: ["合并结果完整可用", "重复项已被清理"],
              input_refs: [],
            },
            {
              id: "todo_deliver",
              title: "交付最终结果",
              description: "整理最终结果并交付，确保内容清晰且可直接使用。",
              priority: "high",
              capability_type: "writing",
              assignee: "single_executor",
              depends_on: ["todo_merge_results"],
              acceptance_criteria: ["最终结果清晰可读", "最终结果内容完整"],
              input_refs: [],
            },
          ],
        }),
      },
    );

    expect(todos).toHaveLength(5);
    expect(todos.filter((todo) => todo.capability_type === "collection")).toHaveLength(2);
    expect(todos[0]?.title).toBe("明确范围");
  });
  it("retries when explicit per-worker counts are inflated to the full total", async () => {
    let callCount = 0;

    const todos = await planInitialTodos(
      "Use 2 parallel subagents to download 10 papers, each subagent downloads 5 papers, then merge and deliver.",
      undefined,
      {
        invokeLlm: async () => {
          callCount += 1;
          if (callCount === 1) {
            return JSON.stringify({
              todos: [
                {
                  id: "todo_collect_1",
                  title: "Download first 10 papers",
                  description: "Download the first 10 requested papers for batch 1.",
                  priority: "high",
                  capability_type: "collection",
                  assignee: "single_executor",
                  depends_on: [],
                  acceptance_criteria: ["10 papers downloaded", "batch 1 manifest created"],
                  input_refs: [],
                },
                {
                  id: "todo_collect_2",
                  title: "Download second 10 papers",
                  description: "Download the second 10 requested papers for batch 2.",
                  priority: "high",
                  capability_type: "collection",
                  assignee: "single_executor",
                  depends_on: [],
                  acceptance_criteria: ["10 papers downloaded", "batch 2 manifest created"],
                  input_refs: [],
                },
                {
                  id: "todo_merge",
                  title: "Merge and deliver",
                  description: "Merge both batches and deliver the final package.",
                  priority: "high",
                  capability_type: "merge",
                  assignee: "single_executor",
                  depends_on: ["todo_collect_1", "todo_collect_2"],
                  acceptance_criteria: ["merged package ready", "delivery report complete"],
                  input_refs: [],
                },
              ],
            });
          }

          return JSON.stringify({
            todos: [
              {
                id: "todo_collect_1",
                title: "Download first 5 papers",
                description: "Download exactly 5 requested papers for batch 1.",
                priority: "high",
                capability_type: "collection",
                assignee: "single_executor",
                depends_on: [],
                acceptance_criteria: ["5 papers downloaded", "batch 1 manifest created"],
                input_refs: [],
              },
              {
                id: "todo_collect_2",
                title: "Download second 5 papers",
                description: "Download exactly 5 requested papers for batch 2.",
                priority: "high",
                capability_type: "collection",
                assignee: "single_executor",
                depends_on: [],
                acceptance_criteria: ["5 papers downloaded", "batch 2 manifest created"],
                input_refs: [],
              },
              {
                id: "todo_merge",
                title: "Merge and deliver 10 papers",
                description: "Merge both 5-paper batches and deliver the final 10-paper package.",
                priority: "high",
                capability_type: "merge",
                assignee: "single_executor",
                depends_on: ["todo_collect_1", "todo_collect_2"],
                acceptance_criteria: ["10-paper merged package ready", "delivery report complete"],
                input_refs: [],
              },
            ],
          });
        },
      },
    );

    expect(callCount).toBe(2);
    expect(todos).toHaveLength(3);
    expect(todos.filter((todo) => todo.capability_type === "collection")).toHaveLength(2);
    expect(todos[0]?.title).toContain("5");
    expect(todos[1]?.title).toContain("5");
  });
});
